# This is a basic workflow to help you get started with Actions
name: Fetch data from github API
on:
  push
#  schedule:
#    - cron: "7/7 * * * *"
#    - cron: "* * * * 0"

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run the python script to get data
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: python -m pip install -r requirements.txt && python main.py

      - name: Push the files to github
        run: |
          git config --global user.email "vittorfpereira@gmail.com"
          git config --global user.name "vittorfp"
          git status
          git add .
          git commit -m "updating data"
          git push
